version: '3'

services:

  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/Chipichapes
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'

  web:
    build: '.'
    depends_on:
      - 'db'
    ports: 
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - 'db:db'

 # frontend:
   # image: networked-aframe 
   # depends_on:
   #   - 'web'
   # ports:
   #   - 8080:8080
   # volumes:
   #   - '.:/app'
  
volumes:
  db: