from neo4j:3.4.14
ENV NEO4J_AUTH=neo4j/Chipichapes
RUN echo dbms.connectors.default_listen_address=0.0.0.0 >> conf/neo4j.conf
RUN echo dbms.connector.bolt.listen_address=0.0.0.0:5000 >> conf/neo4j.conf
ENV NEO4J_PASSWORD=Chipichapes 